<html>
<head>
    <meta charset="utf-8">
    <title>Orders List</title>

    <link rel="stylesheet" href="/css/bootstrap.min.css">
</head>
<body>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
            <table class="table table-striped text-center">
                <tr>
                    <th>ID</th>
                    <th>ФИО</th>
                    <th>Дата рождения</th>
                    <th>ИНН</th>
                    <th>Тип карты</th>
                </tr>


                <?php if ($orders->isEmpty()) : ?>
                    <tr>
                        <td colspan="5">Список пуст</td>
                    </tr>
                <?php else : ?>
                    <?php foreach ($orders as $order) : ?>
                        <tr>
                            <th><?php echo($order['id']); ?></th>
                            <th><?php echo($order['name']); ?></th>
                            <th><?php echo($order['birth']); ?></th>
                            <th><?php echo($order['inn']); ?></th>
                            <th><?php echo($order['type']); ?></th>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </table>
        </div>
    </div>
</div>
</body>
</html>